Feature/landing page
acmutd/comet_planning pull request #128
Opened 2022-03-22 20:28 UTC by lokeshyerneni

[WIP] This is a webpage created for the users to look at when they first enter the Planner website. The inspiration for this was taken from the landing page designed on [Figma](https://www.figma.com/file/cycV0bxP6vTJJYUONFoBr0/Planner-Mockups?node-id=24929%3A31445) in the Main Pages section. As of now, the webpage currently has a static layer with minimal responsiveness and good animation. Lastly, pay no attention to the website when the browser is resized as it will be addressed in the near future when the animations and webpage structure are taken care of. Any feedback regarding animations such as excess animation/lacking animations as well as the structure of the webpage will be appreciated.

2022-03-25 05:45 UTC, ZzRanger commented
Please resolve build issues so that we can preview the deployment on Vercel. You can do this by running "npm run build" on your local machine, then resolving all the errors that appear.

2022-03-25 06:07 UTC, ZzRanger requested changes

2022-03-25 06:07 UTC, ZzRanger commented on components/home/Onboarding/ClassCard.tsx
> +            <CardContent key={index}>
The Degree Plan display should be encapsulated in its own component for re-usability. I would suggest making the new component take in an array of Courses as its props so that it can be used for both Home Page and Main Page.

2022-03-26 05:47 UTC, lokeshyerneni commented on components/home/Onboarding/ClassCard.tsx
> +            <CardContent key={index}>
Resolved temporarily

2022-10-31 02:32 UTC, ZzRanger commented
Closed from #265

2022-10-31 02:32 UTC, closed without merging