Connecting Semesters to Profile
acmutd/comet_planning pull request #420
Opened 2023-02-22 17:41 UTC by Peytonbarre

## Overview
Resolves #357 
Changed the profile page to include the semesters and removed the majors and minors option.

## What Changed
Changed the profile component to remove the majors and minors text fields. Also changed the handle submit to include starting and ending semesters. Changed the user trpc updateUserProfile to allow these changes.

## Other Notes
Had a few problems with non-null assertions. Removed the ones giving in error in useEffect but kept them in for the handleSubmit. Don't know if using non-null assertions is good practice or not, I can change them if needed.

2023-02-22 19:12 UTC, thekevinge requested changes
A few related things (no changes needed for these):
- Currently/planning on migrating off MUI 
- Users shouldn't be able to make their end semester before their start semester, but that'll be in another issue 

Overall good stuff! Great job :tada:

2023-02-22 19:12 UTC, thekevinge commented on src/components/home/Profile.tsx
> +    console.log(firstSem)
Don't forget to delete the console logs :)

2023-02-22 19:16 UTC, thekevinge commented
Oh and also make sure your code is formatted, just noticed the workflow failed. You can run ``npx  prettier -w .`` from the project root or install the VSCode extension (if you use that).

2023-02-23 03:32 UTC, ZzRanger submitted a review, later dismissed
It works good job! Congrats on first issue for the semester :)

2023-02-23 03:32 UTC, ZzRanger commented on src/components/home/Profile.tsx
>      // TODO: Implement changing profile settings here
Oh uhh do that real quick then your good to go

2023-02-23 04:35 UTC, merged