Login page
acmutd/comet_planning pull request #485
Opened 2023-03-04 10:27 UTC by sudoer777

## Overview

For #443 

Changes layout of sign-in page, adds Facebook and Google login methods, and removes email authentication as shown by the Figma design.

## What Changed

src/pages/auth/login.tsx - redid the login page
src/icons/AuthProviderIcons.tsx - added logos for login providers
src/pages/api/auth/[...nextauth].ts - added new providers
.env.example - added env variable fields for new providers

## Other Notes

**The login redirection does not appear to work, so this should be merged into a separate branch until it is fixed (I was not able to select that as an option for the PR)**

2023-03-04 11:05 UTC, sudoer777 commented
Also I had to run `npx prisma generate` so that may need to be added to the README.md

2023-03-04 21:49 UTC, thekevinge requested changes
Looks good overall. Just needs a few changes!

Would it be possible to change Facebook to Instagram?

2023-03-04 21:49 UTC, thekevinge commented on src/server/db/platform_client.ts
> +import { PrismaClient } from '@prisma/client';
This needs to be changed back to ``'../../../prisma/generated/platform/'`` because it's for the API team's database. 

See: 
- #403
- https://github.com/prisma/prisma/issues/2443#issuecomment-630679118

2023-03-04 21:49 UTC, thekevinge commented on src/pages/auth/login.tsx
>                    <button
Mapped elements should take in a ``key`` prop.

2023-03-04 21:49 UTC, thekevinge commented on src/icons/AuthProviderIcons.tsx
> +// {AuthProviderIcons["disc"]}
Remove comment

2023-03-13 02:08 UTC, sudoer777 commented
> Would it be possible to change Facebook to Instagram?

Yes let me do that rn

2023-03-13 03:01 UTC, sudoer777 commented
So it looks like Instagram doesn't have an API for authentication (and it specifically says not to use it for authentication) - it's just meant for viewing profile data.

![image](https://user-images.githubusercontent.com/78781902/224597787-d5462356-9b79-42dc-be34-e2a04039b909.png)

Additionally, the API page seems very restrictive and wants https and URLs for all sorts of stuff:

![image](https://user-images.githubusercontent.com/78781902/224598092-b6035d32-9556-42d4-b4ec-9f3bb5a8099c.png)

And then it requires an app review:

![image](https://user-images.githubusercontent.com/78781902/224598183-d70342ec-219c-4086-8e7c-fa5ba514cc6a.png)

Also, the API [doesn't return the user's email anyway](https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/providers/instagram.js) (since users can sign up with a phone number instead).

So, using Instagram as an authentication method doesn't seem like it will work.

2023-03-13 03:15 UTC, sudoer777 commented on src/pages/auth/login.tsx
>                    <button
Isn't that what `idx` is, or do we need another prop?

2023-03-13 03:26 UTC, sudoer777 commented
More info here: https://stackoverflow.com/questions/58421990/can-we-use-instagram-for-oauth2-login-for-normal-business-and-creator-accounts

2023-03-13 03:30 UTC, sudoer777 commented
Also, should I add instructions for configuring Google/Facebook APIs to readme.md, and should any of that be moved into a GitHub Wiki or something?

2023-04-05 03:50 UTC, closed without merging