Course search
acmutd/comet_planning pull request #493
Opened 2023-03-06 19:47 UTC by Pelps12

## Overview

This PR ads course titles to the search of courses

2023-03-06 21:44 UTC, thekevinge requested changes
Your code looks solid. Thanks for working on this issue. Just a few things I want to point out.

- Ideally, we don't want the toggle. People should be able to type in a course title or catalog code and the correct courses will come up.
- You could use a library for this instead. I'd recommend [FuseJS](https://fusejs.io/), but you can use whatever works.

2023-03-16 21:47 UTC, ZzRanger approved these changes, later dismissed
Tested it and LGTM! I'll merge this later tonight if no other problems come up.

2023-03-16 21:47 UTC, ZzRanger commented on src/components/planner/Sidebar/Sidebar.tsx
> +  React.useEffect(() => {
What is the purpose of this useEffect?

2023-03-17 02:40 UTC, Pelps12 commented on src/components/planner/Sidebar/Sidebar.tsx
> +  React.useEffect(() => {
It's useless if not inefficient. It was to test Fusejs

2023-03-17 02:41 UTC, Pelps12 commented on src/components/planner/Sidebar/Sidebar.tsx
> +  React.useEffect(() => {
Meant to leave my comment here

2023-03-17 03:00 UTC, merged