Sentry setup
acmutd/comet_planning pull request #555
Opened 2023-03-29 23:30 UTC by jasonappah

## Overview

This PR integrates [Sentry](https://sentry.io), which will allow us to keep tabs on any issues that pop up in production and get detailed logs for debugging issues.

List the GitHub issues containing the issues relevant to this pull request.

[For example, "Resolves #1, closes #2, fixes #3", etc.]

Describe your changes here at a high level, describing how this PR fits into the
rest of the project.

## What Changed

Go more into detail about key files that were modified and why they were
updated. Do not list every file that was modified; only note the ones most
relevant to this feature or bug fix.

## Other Notes

If were roadblocks encountered during development that remain unresolved or any
future additions or changes to make, note them here. Otherwise. Feel free to
delete this section if it isn't needed.

2023-04-04 14:45 UTC, ZzRanger requested changes
Imma be real idt I'll be able to properly review this until at least Wed-Thurs so if someone else minds looking at sentry before merge that'd be great. PR seems fine to me aside from updating .env.example

2023-04-04 14:45 UTC, ZzRanger commented on sentry.server.config.js
> +    'https://edb9e327f9024e7599eae859bad9be47@o4504918397353984.ingest.sentry.io/4504924302409728',
I didn't read docs but should this be env file or is this fine?

2023-04-04 14:45 UTC, ZzRanger commented on sentry.client.config.js
> +const SENTRY_DSN = process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN;
Should probably update .env.example too

2023-04-07 19:29 UTC, jasonappah commented on sentry.server.config.js
> +    'https://edb9e327f9024e7599eae859bad9be47@o4504918397353984.ingest.sentry.io/4504924302409728',
This should be fine since this ends up being used in the browser anyway

2023-04-07 19:29 UTC, jasonappah commented on sentry.client.config.js
> +const SENTRY_DSN = process.env.SENTRY_DSN || process.env.NEXT_PUBLIC_SENTRY_DSN;
will do

2023-04-09 18:30 UTC, ZzRanger approved these changes, later dismissed
LGTM!

2023-04-10 19:27 UTC, ZzRanger commented on sentry.client.config.js
> +Sentry.init({
Small thing but should we specify the [environment](https://docs.sentry.io/platforms/javascript/guides/nextjs/configuration/environments/) for Sentry?

2023-04-10 19:47 UTC, jasonappah commented on sentry.client.config.js
> +Sentry.init({
Can't find the docs page that said this but the environment is automatically set from NODE_ENV

2023-04-10 19:50 UTC, jasonappah commented on sentry.client.config.js
> +Sentry.init({
Actually i read that from a legacy docs page - lemme fix

2023-04-10 19:53 UTC, jasonappah commented on sentry.client.config.js
> +Sentry.init({
should be gtg

2023-04-22 05:11 UTC, jasonappah commented
Superseded by #578

2023-04-22 05:11 UTC, closed without merging