Show course names in semester view
acmutd/comet_planning pull request #564
Opened 2023-04-09 16:15 UTC by cubetastic33

NP-19
+ Show the course names in the semester view
+ Show the warning and lock icons next to the course ID
+ Show an ellipse when the course is hovered upon
+ Show the menu only when the ellipse is clicked
+ Only show the option to dismiss pre-reqs when there are prereq warnings

![image](https://user-images.githubusercontent.com/33519300/230783981-0e3752bd-0d48-4daa-acde-0c1d8cde4865.png)

2023-04-11 20:36 UTC, ZzRanger requested changes
Changes look great I really like the hamburger button!! We just need to fix the UI a bit as on laptop screens the summer semesters are cut off. Otherwise great work!

2023-04-11 20:36 UTC, ZzRanger commented on src/components/planner/Tiles/SemesterCourseItem.tsx
> +              <span className="w-72 truncate text-sm">{title}</span>
This is causing issues in the semesters haha.

<img width="1440" alt="Screenshot 2023-04-11 at 3 30 23 PM" src="https://user-images.githubusercontent.com/47403443/231282108-4a122394-2812-48ae-9e7b-ae69e0bc3664.png">

2023-04-11 23:06 UTC, cubetastic33 commented on src/components/planner/Tiles/SemesterCourseItem.tsx
> +              <span className="w-72 truncate text-sm">{title}</span>
Made some changes; should look like this now on small screens

![Screen Shot 2023-04-11 at 18 05 17](https://user-images.githubusercontent.com/33519300/231307278-e8276b14-f9f0-4825-a5a4-88e9fdf15655.png)

2023-04-14 16:45 UTC, thekevinge approved these changes
Looks good! This is super dope to have :)

2023-04-14 16:45 UTC, merged