Add link to catalog on hover
acmutd/comet_planning pull request #577
Opened 2023-04-19 06:21 UTC by cubetastic33

NP-17

Adds a link to the UTD catalog from the course description tooltip in the semester view and sidebar.

2023-04-19 17:19 UTC, thekevinge requested changes

2023-04-19 17:19 UTC, thekevinge commented on src/components/planner/CourseInfoHoverCard.tsx
> +            href={`https://catalog.utdallas.edu/2022/undergraduate/courses/${courseCode
Everything looks good! 

Just one nitpick:
- Could we make the year dependent on the year of their first semester? You can use the ``SemesterContext`` or prop drill it.

2023-04-19 20:04 UTC, cubetastic33 commented on src/components/planner/CourseInfoHoverCard.tsx
> +            href={`https://catalog.utdallas.edu/2022/undergraduate/courses/${courseCode
Only concern I have with that is for example if someone started in Spring 2023 - There is no catalog yet for 2023. Should we just use their first semester capping it at the last Fall?

2023-04-19 20:12 UTC, thekevinge commented on src/components/planner/CourseInfoHoverCard.tsx
> +            href={`https://catalog.utdallas.edu/2022/undergraduate/courses/${courseCode
Oh shoot that's a good point. From what I understand, which catalog you use is based on the Fall semester, so if you started Spring 2023 you still use the "2022" catalog. It kinda implies it [here](https://catalog.utdallas.edu/2022/undergraduate/home) too. For people that start in Fall 2023... we'll have to hope that the uni posts it, and if not we'll deal with it later.

2023-04-20 15:41 UTC, thekevinge approved these changes
Looks good! Will merge at next meeting :+1:

2023-04-25 22:44 UTC, merged