Standardize major names
acmutd/comet_planning pull request #657
Opened 2023-09-08 22:26 UTC by cubetastic33

NP-81

Also fetches list of supported majors directly from validator instead of using a majors.json file.

Couldn't figure out how to rename the `VALIDATOR` env var though, so ended up creating a duplicate env var for now called `NEXT_PUBLIC_VALIDATOR`.

2023-09-09 00:30 UTC, akevinge requested changes
PTAL.

- You'll also need to modify the env schema: https://github.com/UTDNebula/planner/blob/develop/src/env/schema.mjs
- Build workflow: https://github.com/UTDNebula/planner/blob/develop/.github/workflows/build.yml

Don't worry about the integration tests. Also will update this and Vercel envs.

2023-09-09 01:49 UTC, akevinge commented
Ok just updated integration test to run the validator inside the workflow (it was using the deployed instance before). Please rebase and update VALIDATOR in this file as well: https://github.com/UTDNebula/planner/blob/develop/.github/workflows/tests.yml.

2023-09-10 23:10 UTC, cubetastic33 commented on validator/degree_data/Visual Performing Arts Music Concentration(BA).json
> +  "display_name": "Visual and Performing Arts with Music Concentration(BA)",
good point

2023-09-10 23:10 UTC, cubetastic33 commented on validator/degree_data/Visual Performing Arts Music Concentration(BA).json
> +  "uuid": "afcfff81-d8e9-42bd-9e90-1b3a3c4925a5"
oh yeah

2023-09-10 23:11 UTC, cubetastic33 commented on validator/scripts/match_degree_names.py
no

2023-09-10 23:16 UTC, cubetastic33 commented on validator/degree_data/Business Administration(BS)_notready.json
oh yeah

2023-09-10 23:35 UTC, cubetastic33 commented on src/components/planner/EditableMajor.tsx
> +  fetch(`${process.env.NEXT_PUBLIC_VALIDATOR}/get-degree-plans`, {
good idea

2023-09-11 02:04 UTC, cubetastic33 commented on validator/api.py
> +    for fname in glob("./degree_data/*.json"):
ok

2023-09-11 15:09 UTC, akevinge approved these changes, later dismissed
It seems like most of the checks aren't running. Try rebasing.

Also, could you update `VALIDATOR` in the [`e2e test workflow`](https://github.com/UTDNebula/planner/blob/develop/.github/workflows/tests.yml.) and write comments explaining what the hook/endpoint does.

Other than that, lgtm.

2023-09-12 05:42 UTC, akevinge commented
Will update the envs on Vercel. Having issues logging in :thinking:

2023-09-12 23:44 UTC, akevinge approved these changes

2023-09-12 23:45 UTC, merged