NP-43 : fixed keyword highlighting in course description
acmutd/comet_planning pull request #685
Opened 2023-09-26 17:40 UTC by enkyuan

## What Changed

Modified CourseInfoHoverCard.tsx to display description with course and corresponding prerequisite bolded.

2023-09-26 18:44 UTC, akevinge requested changes
The format/lint check is failing. You can run the format via `npm run format`. Also make sure you have the Prettier configured in VSCode.

2023-09-28 04:22 UTC, enkyuan commented
@akevinge format/lint error fixed. Should be ready to merge now unless there's something else I'm missing. Please let me know.

2023-09-28 17:14 UTC, akevinge requested changes

2023-09-28 17:14 UTC, akevinge commented on src/components/planner/CourseInfoHoverCard.tsx
> +        Hdi
I think you might have accidently left this in here.

2023-09-28 17:15 UTC, enkyuan commented on src/components/planner/CourseInfoHoverCard.tsx
> +        Hdi
Will do. Just remove it?

2023-09-28 17:16 UTC, akevinge commented on src/components/planner/CourseInfoHoverCard.tsx
> +        Hdi
Yes.

2023-10-02 15:23 UTC, akevinge approved these changes
LGTM

2023-10-02 15:23 UTC, merged