Add support for versioning degree plans by year
acmutd/comet_planning pull request #703
Opened 2023-10-07 01:57 UTC by cubetastic33

NP-91

Degree plan JSON files are stored by year. If the plan for the requested degree couldn't be found in the requested year, it falls back to the closest year that it is available for that is older than the requested year. If there is no year older than that having it, it falls back to the closest year that occurs after the requested year.

For now the year requested by the front-end is hardcoded to 2022, working on getting that dynamically.

2023-10-07 18:21 UTC, akevinge requested changes

2023-10-07 18:21 UTC, akevinge commented on validator/degree_solver.py
>                  print("Error: degree plan not found!")
Can we raise and bubble up a 404 error instead of printing here?

2023-10-07 22:59 UTC, cubetastic33 commented on validator/degree_solver.py
>                  print("Error: degree plan not found!")
ok

2023-10-08 15:52 UTC, akevinge approved these changes

2023-10-08 15:53 UTC, merged